// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfjTVqQ2tkMASgS8jUqvIY4vKt4Bajsk',
    appId: '1:1033694925470:android:a930b0071665f6f452a18f',
    messagingSenderId: '1033694925470',
    projectId: 'uaspraktikum-22130',
    storageBucket: 'uaspraktikum-22130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYamqgiwnzA-xFJqqPEpIpzC3rs_d3Tk',
    appId: '1:1033694925470:ios:0b8d096d3eeb949c52a18f',
    messagingSenderId: '1033694925470',
    projectId: 'uaspraktikum-22130',
    storageBucket: 'uaspraktikum-22130.firebasestorage.app',
    iosBundleId: 'com.example.projectAkhirSmartcanteen',
  );
}
